route:
  group_by: [Alertname]
  reciever: email-me

recievers:
- name: email-me
  email_configs:
  - to: ayugupta99@gmail.com
    from: ayugupta99@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "ayuguta99@gmail.com"
    auth_identity: "ayugupta99@gmail.com"
    auth_password: "****"
