route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_onterval: 3h
  receiver: slack_general

  routes:
  - match:
     severity: critical
    continue: true
    receiver: webhook


receivers:

- name: slack_general
  slack_configs:
  - api _url: https://hooks.slack.com/services/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
  channel: 'CodeAZ'

- name: webhook
  webhook_configs:
  - url: 'https://hooks.slack.com/services/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'
  send_resolved: false

