global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
rule_files:
  - "rules.yml"


global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'Server1 Node'
    scrape_interval: 2m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http    
    static_configs:
      - targets: ['13.235.241.239:9100']

  - job_name: 'Server1 Redis'
    scrape_interval: 2m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['13.235.241.239:9121']

  - job_name: 'Server1 nginx'
    scrape_interval: 2m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['13.235.241.239:8188']

  - job_name: 'Server1 process'
    scrape_interval: 2m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['13.235.241.239:9256']

  - job_name: 'Server3 Node'
    scrape_interval: 2m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['13.232.194.69:9100']

  - job_name: 'Server3 Redis'
    scrape_interval: 2m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['13.232.194.69:9121']

  - job_name: 'Server3 nginx'
    scrape_interval: 2m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['13.232.194.69:8188']

  - job_name: 'Server3 process'
    scrape_interval: 2m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['13.232.194.69:9256']







