---
- name: Add the user nginx-exporter
  user:
    name: nginx_exporter
    shell: /sbin/nologin


- name: Copying the binary file
  copy:
    src: "nginxlog_exporter"
    dest: "/usr/local/bin/"
    mode: 0755

- name: Nginx config file
  copy:
    src: "nginxlog_config.yml"
    dest: /etc/nginxlog_exporter/
    mode: 0755
  

- name: Create Nginx Exporter Service
  template:
    src: "nginx-exporter.j2"
    dest: /etc/systemd/system/nginx_exporter.service
    mode: 0755

- name: Daemon reload for Nginx Exporter
  systemd:
    name: nginx_exporter
    daemon_reload: yes

- name:  Enable Nginx Exporter service
  systemd:
    name: nginx_exporter
    state: started
    enabled: yes


