---
- name: Add the user node-exporter
  user:
    name: node_exporter
    shell: /sbin/nologin
    
- name: Copying the binary file
  copy:
    src: "node_exporter"
    dest: "/usr/local/bin/"
    mode: 0755


- name: Create Node Exporter Service
  template:
    src: "node-exporter.j2"
    dest: /etc/systemd/system/node_exporter.service
    mode: 0755

- name: Daemon reload for Node Exporter
  systemd:
    name: node_exporter
    daemon_reload: yes

- name:  Enable Node Exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
