---
- name: Adding user for Redis Exporter
  user:
    name: redis_exporter
    shell: /sbin/nologin

- name: Copying the binary file
  copy:
    src: "redis_exporter"
    dest: "/usr/local/bin/"
    mode: 0755

- name: Creating Service for Redis Exporter
  template:
    src: redis-exporter.j2
    dest: /etc/systemd/system/redis_exporter.service
    mode: 0755

- name: Daemon reload for redis Exporter
  systemd:
    name: redis_exporter
    daemon_reload: yes

- name: Enabling and starting the service for redis Exporter
  systemd:
    name: redis_exporter
    daemon_reload: yes
    state: started
    enabled: yes